#!/bin/bash

# t3.sh
# Get Single BOOKmark
set +x

mkdir -p /tmp/ffbookmarks



# single argument (tag)

#-----------------------------------------------
# make sure the app is available
which sqlite3 >/dev/null
if [ $? != 0 ]
then
	echo "sqlite3 is not available, please install first"
	exit 1
fi

#-----------------------------------------------
# Fetch default profile folder of current user
str=$(grep Default ~/.mozilla/firefox/profiles.ini)

if [ $? != 0 ]
then
	echo "Error: unable to fetch current user's default profile"
	exit 1
fi
# split string
IFS=" ";read -a tab1 <<< "$str"
echo "tab1=$tab1"
IFS="=";read -a tab2 <<< "${tab1[0]}"
echo "tab2=$tab2"
folder=${tab2[1]}

fin=/home/sk/.mozilla/firefox/$folder/places.sqlite
echo "fin=$fin"
if ! [ -e $fin ]
then
	echo "Error, file $fin does not exist"
	exit 2
fi


# check if argument (tag) is given. If not, print the list of tags
nb=$#
if [ $nb == 0 ]
then
	echo "error, you need to give a tag"
	echo ".open $fin" >temp_command
	echo "select title from moz_bookmarks where parent=4;" >>temp_command
	sqlite3 <temp_command >/tmp/gsb0.txt
	nb=$(cat /tmp/gsb0.txt | wc -l)
	echo "available tags: $nb"

	for a in $(cat /tmp/gsb0.txt);
	do
		echo -n "$a - "
	done
	echo ""
	exit 1
fi

IFS=$' \t\n'

# 1 - Fetch the tag id in table moz_bookmarks
echo ".open $fin" >temp_command
echo "select id from moz_bookmarks where title='$1' AND type=2;" >>temp_command
sqlite3 <temp_command >out1.txt

rm out2.txt
for index in $(cat out1.txt)
do
	echo "index=$index"
	
	# 2 - Fetch the list of URL ids having that tag
	echo ".open $fin" >temp_command
	echo "select fk from moz_bookmarks where parent='$index';" >>temp_command
	sqlite3 <temp_command >>out2.txt
done

echo "out2 size=$(wc -l out2.txt)"
fk=$(cat out2.txt)

# get other tags with same URL
echo ".open $fin" >temp_command
echo "select parent from moz_bookmarks where fk='$fk';" >>temp_command
sqlite3 <temp_command >out4.txt

rm out5.txt
for tag in $(cat out4.txt)
do
	echo "tag=$tag"
	echo ".open $fin" >temp_command
#	echo "select title from moz_bookmarks where id='$tag' AND position=0;" >>temp_command
	echo "select title from moz_bookmarks where id='$tag' AND position=0;" >>temp_command
	sqlite3 <temp_command >>out5.txt
done

exit

# 3 - Fetch the URLs from table moz_places using the indexes previously extracted
rm out3.txt
echo ".open $fin" >temp_command
for a in $(cat out2.txt);
do
#	echo "a=$a"
	echo "select url from moz_places where id='$a';" >>temp_command
done
sqlite3 <temp_command >>out3.txt

# 4 - generate output html file
nblinks=$(cat out3.txt|wc -l)
fout=gsbook.html
echo -e "<html>\n<head>\n<title>gsbook output</title>" >$fout
echo -e "</head>\n<body>" >>$fout
echo -e "<h1>tag: $1 ($nblinks links)</h1>" >>$fout
echo -e "<ul>" >>$fout
for link in $(cat out3.txt)
do
	echo -e "<li><a href='$link'>$link</a></li>\n" >>$fout
done
echo -e "</ul>\n</body>\n</html>" >>$fout

# open output file in browser
xdg-open $fout; echo ""



